### ISSUE TITLE
Expose interface for binding a vblank callback

### ISSUE THREAD

**Issue by corymonroe** [nnarain/gameboycore#142]
How would you feel about exposing an interface for binding a vblank callback in [gpu.cpp](https://github.com/nnarain/gameboycore/blob/master/src/core/gpu.cpp#L125) much in the same way you have exposed the interface for binding a scanline callback.

This would allow bindings to execute at the time the vblank line is reached, rather than line 143.

Not a huge deal, but just something I noticed / was curious about when looking through the code.

**Comment by nnarain** [comment]
Yup firing a callback from the core for that makes sense.

**Comment by nnarain** [comment]
Added a vblank callback.

Merged to develop branch.
